### ISSUE TITLE
Windows: undefined method `epub_stylesheet` for Paru/Pandoc

### ISSUE THREAD

**Issue by Enviii** [captn3m0/cosmere-books#7]
I tried to find an API where epub_stylesheet was referenced for Paru or Pandoc, but I couldn't find anything. Again, this worked fine in my Ubuntu VM. Doesn't work in Windows. 

```
[html] Generated HTML file
C:/Users/dkark/Documents/GitHub/cosmere-books/methods.rb:54:in `block in gen_epub': undefined method `epub_stylesheet' for #<Paru::Pandoc:0x0000000005389de8> (NoMethodError)
Did you mean?  epub_chapter_level
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/paru-0.3.0.0/lib/paru/pandoc.rb:137:in `instance_eval'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/paru-0.3.0.0/lib/paru/pandoc.rb:137:in `configure'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/paru-0.3.0.0/lib/paru/pandoc.rb:107:in `initialize'
        from C:/Users/dkark/Documents/GitHub/cosmere-books/methods.rb:49:in `new'
        from C:/Users/dkark/Documents/GitHub/cosmere-books/methods.rb:49:in `gen_epub'
        from C:/Users/dkark/Documents/GitHub/cosmere-books/methods.rb:93:in `generate'
        from oathbringer.rb:67:in `<main>'
```

**Comment by chinhodado** [comment]
I'm having the same issue

**Comment by captn3m0** [comment]
Thanks for the report. I'll take a look tonight

**Comment by chinhodado** [comment]
It's because of [this](https://github.com/htdebeer/paru/issues/36). Solution is to use pandoc 1.9 instead.

**Comment by captn3m0** [comment]
Thanks for investigating this. I'm waiting for [pandoc-bin](https://aur.archlinux.org/packages/pandoc-bin/) to get updated, but have pushed a fix for the issue, removing the dependency on `epub_stylesheet`.
